project_id = "dvqmzqnmgndfphemfief"

[functions.get-client-leads]
verify_jwt = true

[functions.get-lead-details]
verify_jwt = true

[functions.submit-lead]
verify_jwt = true

[functions.get-all-leads-admin]
verify_jwt = true

[functions.get-system-stats]
verify_jwt = true

[functions.assign-lead-to-client]
verify_jwt = true

[functions.update-lead-status]
verify_jwt = true

[functions.update-lead]
verify_jwt = true

[functions.update-lead-feedback]
verify_jwt = true

[functions.delete-lead]
verify_jwt = true

[functions.invite-client]
verify_jwt = true

[functions.validate-notion-database]
verify_jwt = true

[functions.reset-client-password]
verify_jwt = true

[functions.get-orders]
verify_jwt = true

[functions.get-order-details]
verify_jwt = true

[functions.create-order]
verify_jwt = true

[functions.update-order]
verify_jwt = true
